MAX_FIELD_SIZE = 76
MAX = MAX_FIELD_SIZE - 1
MIN = 0
SLEEP_BETWEEN_DRAW_GRAPH = 0.5
SLEEP_BETWEEN_SCAN_ITERATION = 0.7
MS_TO_UPDATE_GRAPH = 50

CORRECTION_Z = 5
MULTIPLICITY = 1
SERVO_X = 'servo_x'
SERVO_Y = 'servo_y'
SERVO_Z = 'servo_z'
DTO_X = 'x'
DTO_Y = 'y'
DTO_Z = 'z'
